In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

df = pd.read_csv("sampledata.csv")
df

   Column1  Column2 Column3  Column4  Column5
0        1       78       A    -0.61    False
1        2       94       C    -0.90     True
2        3       59       B    -0.17     True
3        4       32       C    -2.74    False
4        5       65       B     1.14     True
5        6       94       D    -0.76     True
6        7       21       A    -1.48    False
7        8       74       D    -0.37     True
8        9       37       D     1.00    False
9       10       27       A    -0.27     True

In [ ]:
df.columns #lists all the names of columns

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5'], dtype='object')

In [ ]:
df.info() # information of data stored

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  10 non-null     int64
 1   Column2  10 non-null     int64
 2   Column3  10 non-null     object
 3   Column4  10 non-null     float64
 4   Column5  10 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(1)
memory usage: 462.0+ bytes

In [ ]:
df.shape #total no. of rows and columns

(10, 5)

In [12]:
#df.describe() #statistical summary of interger type data columns
df.describe(include='all') #all summary regardless to the datatypes

         Column1   Column2 Column3    Column4 Column5
count   10.00000  10.00000      10  10.000000      10
unique       NaN       NaN       4        NaN       2
top          NaN       NaN       A        NaN    True
freq         NaN       NaN       3        NaN       6
mean     5.50000  58.10000     NaN  -0.516000     NaN
std      3.02765  27.37578     NaN   1.122172     NaN
min      1.00000  21.00000     NaN  -2.740000     NaN
25%      3.25000  33.25000     NaN  -0.865000     NaN
50%      5.50000  62.00000     NaN  -0.490000     NaN
75%      7.75000  77.00000     NaN  -0.195000     NaN
max     10.00000  94.00000     NaN   1.140000     NaN

In [18]:
#1.remove columns and rows
#df = df.drop(columns=["Column4"])
df = df.drop([5])
df

   Column1  Column2 Column3  Column5
0        1       78       A    False
1        2       94       C     True
2        3       59       B     True
3        4       32       C    False
4        5       65       B     True
6        7       21       A    False
7        8       74       D     True
8        9       37       D    False
9       10       27       A     True

In [ ]:
#add new column
names=['rakesh','ram','shyamn','abc', 'hari', 'lal', 'don', 'rabi', 'gulal']
df["Names"] = names
df

   Column1  Column2 Column3  Column5   Names
0        1       78       A    False  rakesh
1        2       94       C     True     ram
2        3       59       B     True  shyamn
3        4       32       C    False     abc
4        5       65       B     True    hari
6        7       21       A    False     lal
7        8       74       D     True     don
8        9       37       D    False    rabi
9       10       27       A     True   gulal

In [32]:
#df.set_index('Names', inplace= True)
print(df)

        Column1  Column2 Column3  Column5
Names
rakesh        1       78       A    False
ram           2       94       C     True
shyamn        3       59       B     True
abc           4       32       C    False
hari          5       65       B     True
lal           7       21       A    False
don           8       74       D     True
rabi          9       37       D    False
gulal        10       27       A     True